/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package chatapplication;

import com.mysql.cj.jdbc.StatementImpl;
import java.awt.BorderLayout;
import java.awt.Container;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * Ref1: https://www.geeksforgeeks.org/java-swing-jpanel-with-examples/#:~:text=JPanel%2C%20a%20part%20of%20the,not%20have%20a%20title%20bar.
 * Ref2: https://stackoverflow.com/questions/8203824/problems-dynamically-changing-jpanels-on-jframe
 * Ref3: https://stackoverflow.com/questions/6714045/how-to-resize-jlabel-imageicon
 * Ref4: https://www.w3schools.com/java/java_files_read.asp
 * Ref5: https://www.w3schools.com/java/java_files_create.asp
 */
public class Main extends javax.swing.JFrame {

    protected JPanel chatPanel = new ChatPanel();
    protected JPanel settingsPanel = new SettingsPanel();
    protected JPanel signupPanel = new SignupPanel();
    protected JPanel contactsPanel = chatPanel;
    
    protected Container contentPane = null;
    protected JPanel activePanel = chatPanel;
    protected JPanel previousPanel = chatPanel;
    
    protected static Connection dbConnection = null;
    protected static JFrame mainInstance = null;
    
    protected int myUserId = -1;
    protected int receiverId = -1;
    
    /**
     * Startup function
     */
    public Main() {
        initComponents();
        
        // Initialize database
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            dbConnection = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/chat_app", "admin", "1234");
            if (dbConnection == null) {
                System.out.println("Database error!");
            }
        } catch (ClassNotFoundException | SQLException e) {
            System.out.println("Database connection error!");
        }
        
        // myUserId = -1 means no user assigned
        if (myUserId == -1)
        {
            try {
                File config = new File("data.txt");
                if (config.exists() && config.length() != 0) {
                    Scanner sc = new Scanner(config);
                    String line = sc.nextLine();
                    System.out.println(line);
                    myUserId = Integer.parseInt(line.split(":")[1]);
                } else {
                    // Cannot find configuration file -> create new one and insert data
                    config.createNewFile();
                    activePanel = signupPanel;
                }
            } catch (IOException e) {
                System.out.println("Error: reading or writing to config file!");
            }
        }
        
        // Check user is in database?, if not show registration form
        try {
            StatementImpl stmt = (StatementImpl) dbConnection.createStatement();
            String sql = "SELECT * FROM chat_user WHERE user_id=" + myUserId;
            ResultSet resultSet = stmt.executeQuery(sql);
            if (!resultSet.next()) {
                // User is not in the db show registration
                activePanel = signupPanel;
            } else {
                // User found in the db
                myUserId = resultSet.getInt("user_id");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        // User found! show contacts form
        // TODO: set receiverId and show chat panel for that receiver
        
        contentPane = getContentPane();
        contentPane.setLayout(new BorderLayout());
        contentPane.add(activePanel, BorderLayout.CENTER);
    }
    
    public void setActivePanel(JPanel panel) {
        if (contentPane != null) {
            previousPanel = activePanel;
            contentPane.remove(activePanel);
            activePanel = panel;
            contentPane.add(activePanel, BorderLayout.CENTER);
            pack();
        }
        
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simple Chat Application");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 665, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static JFrame getInstance() {
        if (mainInstance == null) {
            mainInstance = new Main();
        }
        
        return mainInstance;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                Main.getInstance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
